#!/usr/bin/env bash
#
# run-local.sh — start the feature-limited Signal-Server test instance.
#
# Generated by install-deps.sh. Edit freely; re-running install-deps.sh will
# overwrite this file.
#
# This uses LocalWhisperServerService, which loads service/src/test/resources/
# config/test.yml + test-secrets-bundle.yml. DynamoDB and Redis are spun up
# automatically inside Docker via testcontainers; external services (CDS, SVR,
# registration, payments, push) are stubbed.
#
# Offline by default: assumes ~/.m2/repository was warmed by install-deps.sh
# and all required Docker images are cached locally. Pass --online to re-allow
# Maven network access (e.g. after upgrading a dependency).
#
# Override the config path with SIGNAL_SERVER_CONFIG=/path/to/your.yml

set -euo pipefail
cd -- "$(dirname -- "${BASH_SOURCE[0]}")"

OFFLINE_FLAG="-o"
EXTRA_ARGS=()
for a in "$@"; do
  case "$a" in
    --online) OFFLINE_FLAG="" ;;
    *)        EXTRA_ARGS+=("$a") ;;
  esac
done

if ! docker info >/dev/null 2>&1; then
  echo "Docker is not reachable — start it with: sudo systemctl start docker" >&2
  echo "If you just ran install-deps.sh, you may also need to re-login so your" >&2
  echo "user picks up the docker group membership (or run: newgrp docker)." >&2
  exit 1
fi

# Silence mvnw warnings: JAVA_HOME unset, and JDK 25's restricted-method warning
# that jansi (Maven's terminal color lib) trips. Both are cosmetic but noisy.
export JAVA_HOME="${JAVA_HOME:-/usr/lib/jvm/temurin-25-jdk-amd64}"
export MAVEN_OPTS="${MAVEN_OPTS:---enable-native-access=ALL-UNNAMED}"

# Prevent the AWS / Google SDKs from probing 169.254.169.254 (EC2 IMDS) and
# metadata.google.internal looking for credentials. Without these, startup can
# stall for ~30s per SDK on hosts with no network, before falling through to
# the static credentials configured in test.yml.
export AWS_EC2_METADATA_DISABLED="${AWS_EC2_METADATA_DISABLED:-true}"
export NO_GCE_CHECK="${NO_GCE_CHECK:-true}"

# Pin the testcontainers reaper image to one install-deps.sh pre-pulled. If
# that pull failed (or the testcontainers library wants a different tag), the
# RYUK_DISABLED fallback below makes startup proceed without a reaper — at the
# cost of leaving orphaned containers around if this script is killed with -9.
export TESTCONTAINERS_RYUK_CONTAINER_IMAGE="${TESTCONTAINERS_RYUK_CONTAINER_IMAGE:-testcontainers/ryuk:0.11.0}"
if ! docker image inspect "$TESTCONTAINERS_RYUK_CONTAINER_IMAGE" >/dev/null 2>&1; then
  echo "[run-local.sh] ryuk image $TESTCONTAINERS_RYUK_CONTAINER_IMAGE not cached; disabling ryuk." >&2
  export TESTCONTAINERS_RYUK_DISABLED=true
fi

# testcontainers' "startup check" pings a public registry by default; disable.
export TESTCONTAINERS_CHECKS_DISABLE="${TESTCONTAINERS_CHECKS_DISABLE:-true}"

exec ./mvnw $OFFLINE_FLAG -Ptest-server,exclude-spam-filter integration-test -DskipTests=true "${EXTRA_ARGS[@]}"
